export const data = [
  {
    id: 1,
    name: "Double Cheeseburger",
    category: "burger",
    image: require("../assets/Double Cheeseburger.jpg"),
    price: "$$$$",
  },
  {
    id: 2,
    name: "Bacon Cheeseburger",
    category: "burger",
    image: require("../assets/Bacon Cheeseburger.jpg"),
    price: "$",
  },
  {
    id: 3,
    name: "Mushroom Burger",
    category: "burger",
    image: require("../assets/Mushroom Burger.jpg"),
    price: "$$",
  },
  {
    id: 4,
    name: "Loaded Burger",
    category: "burger",
    image: require("../assets/Loaded Burger.jpg"),
    price: "$$$",
  },
  {
    id: 5,
    name: "Feta & Spinnach",
    category: "pizza",
    image: require("../assets/Feta & Spinnach.jpg"),
    price: "$$",
  },
  {
    id: 6,
    name: "Supreme Pizza",
    category: "pizza",
    image: require("../assets/Supreme Pizza.jpg"),
    price: "$$$",
  },
  {
    id: 7,
    name: "Meat Lovers",
    category: "pizza",
    image: require("../assets/Meat Lovers.jpg"),
    price: "$$$$",
  },
  {
    id: 8,
    name: "Cheese Pizza",
    category: "pizza",
    image: require("../assets/Cheese Pizza.jpg"),
    price: "$",
  },
  {
    id: 9,
    name: "Kale Salad",
    category: "salad",
    image: require("../assets/Kale Salad.jpg"),
    price: "$$",
  },
  {
    id: 10,
    name: "Ceasar Salad",
    category: "salad",
    image: require("../assets/Ceasar Salad.jpg"),
    price: "$$$",
  },
  {
    id: 11,
    name: "Loaded Salad",
    category: "salad",
    image: require("../assets/Loaded Salad.jpg"),
    price: "$$$$",
  },
  {
    id: 12,
    name: "Fruit Salad",
    category: "salad",
    image: require("../assets/Fruit Salad.jpg"),
    price: "$",
  },
  {
    id: 13,
    name: "Wings",
    category: "chicken",
    image: require("../assets/Wings.jpg"),
    price: "$$",
  },
  {
    id: 14,
    name: "Baked Chicken",
    category: "chicken",
    image: require("../assets/Baked Chicken.jpg"),
    price: "$$$$",
  },
  {
    id: 15,
    name: "Chicken Tenders",
    category: "chicken",
    image: require('../assets/Chicken Tenders.jpg'),
    price: "$",
  },
  {
    id: 16,
    name: "Chicken Kabob",
    category: "chicken",
    image: require('../assets/Chicken Kabob.jpg'),
    price: "$$$",
  },
];

export const categories = [
  {
    id: 1,
    name: "Fast Food",
    image: require('../assets/Fast Food.png'),
  },
  {
    id: 2,
    name: "Pizza",
    image: require('../assets/Pizza.png'),
  },
  {
    id: 3,
    name: "Wings",
    image: require('../assets/Wings.png'),
  },
  {
    id: 4,
    name: "Indian",
    image: require('../assets/Indian.png'),
  },
  {
    id: 5,
    name: "Latest Deals",
    image: require('../assets/Latest Deals.png'),
  },
  {
    id: 6,
    name: "Restaurant Rewards",
    image: require('../assets/Restaurant Rewards.png'),
  },
  {
    id: 7,
    name: "Best Overall",
    image: require('../assets/Best Overall.png'),
  },
  {
    id: 8,
    name: "Shipped Free",
    image: require('../assets/Shipped Free.png'),
  },
];